<x-layouts.app :title="'Kandidat Assignment PIC'">
    <section class="space-y-5">
        <div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><a href="{{ route('assignments.index') }}" class="text-sm font-bold text-brand hover:underline">← Kembali ke Assignment PIC</a><p class="page-eyebrow mt-5">Seleksi calon assignment</p><h2 class="page-title">100 Kandidat Potensial</h2><p class="page-copy">{{ $period->year }} · {{ $period->quarter }}. Hanya perusahaan Non-UMK yang belum memiliki LKPM <strong>Disetujui</strong> pada periode aktif dan memiliki potensi lebih dari Rp0.</p></div><span class="status-pill self-start bg-amber-50 text-amber-800 lg:self-auto">Buffer: Rp {{ number_format($period->buffer_amount, 0, ',', '.') }}</span></div>
        <form method="POST" action="{{ route('assignments.candidates.assign') }}" class="surface-card flex flex-col justify-between gap-4 border border-teal-200 p-4 sm:flex-row sm:items-center"><div><p class="font-bold text-ink">Siap membagi kandidat ke PIC?</p><p class="mt-1 text-sm text-slate-600">100 kandidat utama menjadi tugas aktif. Hingga 100 kandidat cadangan dibagikan sebagai standby dan akan aktif otomatis bila proyeksi tim kurang dari buffer.</p></div>@csrf<button class="primary-action shrink-0" type="submit">Bagi rata kandidat ke PIC</button></form>

        <div class="grid gap-4 md:grid-cols-3"><div class="surface-card p-5"><p class="text-xs font-bold uppercase tracking-wider text-slate-500">Kandidat utama</p><p class="mt-2 text-2xl font-black text-ink">{{ number_format($primaryCandidates->count()) }}</p><p class="mt-1 text-sm text-slate-500">Menjadi tugas aktif awal</p></div><div class="surface-card p-5"><p class="text-xs font-bold uppercase tracking-wider text-slate-500">Potensi gap kasar</p><p class="mt-2 text-2xl font-black text-ink">Rp {{ number_format($primaryPotential, 0, ',', '.') }}</p><p class="mt-1 text-sm text-slate-500">Untuk urutan prioritas, bukan proyeksi TW</p></div><div class="surface-card p-5 ring-1 ring-amber-200"><p class="text-xs font-bold uppercase tracking-wider text-slate-500">Kandidat cadangan</p><p class="mt-2 text-lg font-black text-amber-800">{{ number_format($reserveCandidates->count()) }} standby</p><p class="mt-1 text-sm text-slate-500">Aktif otomatis dari hasil konfirmasi PIC.</p></div></div>

        <section class="surface-card overflow-hidden"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-bold text-ink">100 Perusahaan Berpotensi</h3><p class="mt-1 text-xs text-slate-500">Urutan dari potensi investasi terbesar. Daftar ini digunakan Kabag untuk meninjau kandidat sebelum pembagian rata assignment.</p></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100 text-sm"><thead class="bg-slate-50/80 text-left text-[11px] font-bold uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3.5">Peringkat</th><th class="px-5 py-3.5">Perusahaan</th><th class="px-5 py-3.5">NIB</th><th class="px-5 py-3.5">Proyek</th><th class="px-5 py-3.5 text-right">Potensi gap</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($primaryCandidates as $index => $candidate)<tr class="transition hover:bg-teal-50/40"><td class="px-5 py-4"><span class="grid size-8 place-items-center rounded-lg bg-amber-100 text-xs font-black text-amber-800">#{{ $index + 1 }}</span></td><td class="px-5 py-4 font-bold text-ink">{{ $candidate->name }}<p class="mt-1 text-xs font-normal text-slate-500">{{ $candidate->district ?: 'Lokasi belum tersedia' }}</p></td><td class="px-5 py-4 text-slate-600">{{ $candidate->nib }}</td><td class="px-5 py-4 font-semibold text-slate-700">{{ number_format($candidate->project_count) }} proyek</td><td class="px-5 py-4 text-right font-black text-ink">Rp {{ number_format($candidate->potential, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">Belum ada kandidat yang memenuhi kriteria.</td></tr>@endforelse</tbody></table></div></section>

        <section class="surface-card overflow-hidden"><div class="border-b border-amber-100 bg-amber-50/60 px-5 py-4"><h3 class="font-bold text-amber-950">100 Perusahaan Cadangan</h3><p class="mt-1 text-xs text-amber-800">Cadangan selalu dibagi sebagai standby. Sistem mengaktifkannya otomatis per putaran empat PIC saat proyeksi terkonfirmasi tim masih kurang dari buffer dan muncul hasil konfirmasi berisiko.</p></div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100 text-sm"><thead class="bg-slate-50/80 text-left text-[11px] font-bold uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3.5">Urutan cadangan</th><th class="px-5 py-3.5">Perusahaan</th><th class="px-5 py-3.5">NIB</th><th class="px-5 py-3.5">Proyek</th><th class="px-5 py-3.5 text-right">Potensi gap</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($reserveCandidates as $index => $candidate)<tr class="transition hover:bg-amber-50/50"><td class="px-5 py-4"><span class="grid size-8 place-items-center rounded-lg bg-slate-100 text-xs font-black text-slate-600">#{{ $index + 101 }}</span></td><td class="px-5 py-4 font-bold text-ink">{{ $candidate->name }}<p class="mt-1 text-xs font-normal text-slate-500">{{ $candidate->district ?: 'Lokasi belum tersedia' }}</p></td><td class="px-5 py-4 text-slate-600">{{ $candidate->nib }}</td><td class="px-5 py-4 font-semibold text-slate-700">{{ number_format($candidate->project_count) }} proyek</td><td class="px-5 py-4 text-right font-black text-ink">Rp {{ number_format($candidate->potential, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">Tidak tersedia kandidat cadangan tambahan.</td></tr>@endforelse</tbody></table></div></section>
    </section>
</x-layouts.app>
