<x-layouts.app title="Assignment PIC">
    <section class="flex flex-wrap items-end justify-between gap-5">
        <div><p class="page-eyebrow">{{ $period ? $period->quarter.' '.$period->year : 'Periode belum aktif' }}</p><h2 class="page-title">{{ auth()->user()->role === 'pic' ? 'Tugas Saya' : 'Assignment PIC' }}</h2><p class="page-copy">Jumlah perusahaan dibagi rata. Urutan tugas mengutamakan perusahaan berpotensi besar yang belum LKPM Disetujui pada periode aktif.</p></div>
        @if (auth()->user()->role === 'kepala_bagian')<a href="{{ route('assignments.candidates') }}" class="primary-action">Kandidat 100 + Cadangan <span aria-hidden="true">↗</span></a>@endif
    </section>

    <section class="surface-card mt-7 overflow-hidden">
        <div class="flex items-center justify-between gap-4 border-b border-slate-100 px-5 py-4"><div><h3 class="font-bold text-ink">Daftar perusahaan</h3><p class="mt-1 text-xs text-slate-500">Kandidat utama berstatus aktif; kandidat cadangan akan otomatis aktif jika proyeksi tim kurang dari buffer.</p></div><span class="status-pill bg-teal-50 text-brand">{{ number_format($assignments->total()) }} dibagikan</span></div>
        <div class="hidden overflow-x-auto md:block"><table class="min-w-full divide-y divide-slate-100 text-sm"><thead class="bg-slate-50/80 text-left text-[11px] font-bold uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3.5">Prioritas & perusahaan</th><th class="px-5 py-3.5">PIC</th><th class="px-5 py-3.5">Status tugas</th><th class="px-5 py-3.5">Proyek & sektor</th><th class="px-5 py-3.5"><span class="sr-only">Aksi</span></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($assignments as $assignment)@php($latestFollowUp = $assignment->followUps->first())<tr class="transition hover:bg-teal-50/40"><td class="px-5 py-4"><div class="flex gap-3"><span class="grid size-8 shrink-0 place-items-center rounded-lg {{ $assignment->queue_type === 'primary' ? 'bg-amber-100 text-amber-800' : 'bg-slate-100 text-slate-600' }} text-xs font-black">#{{ $assignment->priority_rank }}</span><div><p class="font-bold text-ink">{{ $assignment->company->name }}</p><p class="mt-1 text-xs text-slate-500">NIB {{ $assignment->company->nib }} · {{ $assignment->company->district ?: 'Lokasi belum ada' }}</p><p class="mt-2 text-xs text-slate-600">{{ $assignment->queue_type === 'primary' ? 'Kandidat utama' : 'Kandidat cadangan' }} · Potensi Rp {{ number_format($assignment->potential_at_assignment, 0, ',', '.') }}</p></div></div></td><td class="px-5 py-4 font-semibold text-slate-700">{{ $assignment->pic->name }}</td><td class="px-5 py-4"><span class="status-pill {{ $assignment->is_task_active ? 'bg-teal-50 text-brand' : 'bg-slate-100 text-slate-600' }}">{{ $assignment->is_task_active ? 'Tugas aktif' : 'Standby' }}</span><p class="mt-2 text-xs font-medium text-slate-600">Verifikasi: {{ str($latestFollowUp?->verification_status ?? 'belum')->replace('_', ' ')->title() }}</p></td><td class="px-5 py-4"><p class="font-semibold text-ink">{{ $assignment->company->projects->count() }} proyek</p><p class="mt-1 max-w-xs text-xs leading-5 text-slate-500">{{ $assignment->company->projects->pluck('sector')->filter()->unique()->join(', ') ?: 'Sektor belum dipetakan' }}</p></td><td class="px-5 py-4 text-right"><a href="{{ route('assignments.show', $assignment) }}" class="text-sm font-bold text-brand hover:underline">Buka detail →</a></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">Belum ada assignment. Buka Kandidat 100 + Cadangan untuk membuat pembagian.</td></tr>@endforelse</tbody></table></div>
        <div class="grid divide-y divide-slate-100 md:hidden">@forelse ($assignments as $assignment)@php($latestFollowUp = $assignment->followUps->first())<article class="p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="font-bold text-ink">{{ $assignment->company->name }}</p><p class="mt-1 text-xs text-slate-500">NIB {{ $assignment->company->nib }}</p></div><span class="status-pill shrink-0 bg-amber-50 text-amber-800">{{ str($latestFollowUp?->verification_status ?? 'belum')->replace('_', ' ')->title() }}</span></div><div class="mt-4 grid grid-cols-2 gap-3 text-xs"><div class="rounded-xl bg-slate-50 p-3"><p class="text-slate-500">PIC</p><p class="mt-1 font-bold text-ink">{{ $assignment->pic->name }}</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-slate-500">Proyek</p><p class="mt-1 font-bold text-ink">{{ $assignment->company->projects->count() }} proyek</p></div></div><a href="{{ route('assignments.show', $assignment) }}" class="mt-4 inline-flex text-sm font-bold text-brand">Lihat detail →</a></article>@empty<p class="px-5 py-12 text-center text-sm text-slate-500">Belum ada assignment aktif.</p>@endforelse</div>
    </section>
    <div class="mt-5">{{ $assignments->links() }}</div>
</x-layouts.app>
