<x-layouts.app title="Periode dan Target">
    <section><p class="page-eyebrow">Kepala Bagian</p><h2 class="page-title">Periode aktif dan target</h2><p class="page-copy">Buat periode berikutnya, lalu aktifkan satu periode kerja. Target periode dihitung otomatis dengan rumus carry-over dari target tahunan dan realisasi sebelum periode.</p></section>
    <section class="mt-7 grid gap-5 xl:grid-cols-[minmax(22rem,.85fr)_minmax(0,1.15fr)]">
        <form method="POST" action="{{ route('periods.store') }}" class="surface-card p-6">@csrf<h3 class="font-bold text-ink">Buat atau perbarui periode</h3><div class="mt-5 grid gap-4"><div class="grid grid-cols-2 gap-3"><label class="grid gap-1 text-sm font-bold">Tahun<input name="year" type="number" min="2021" max="2100" value="{{ old('year', now()->year) }}" required class="rounded-xl"></label><label class="grid gap-1 text-sm font-bold">Triwulan<select name="quarter" required class="rounded-xl"><option>TW I</option><option>TW II</option><option selected>TW III</option><option>TW IV</option></select></label></div>
            @foreach (['annual_target' => ['Target tahunan', 7900000000000, true], 'baseline_realization' => ['Realisasi sebelum periode', 2810000000000, true], 'buffer_amount' => ['Buffer sasaran utama', 3200000000000, false]] as $field => [$label, $default, $required])<label class="grid gap-1 text-sm font-bold">{{ $label }}<div class="relative"><span class="pointer-events-none absolute inset-y-0 left-0 grid w-11 place-items-center text-sm font-bold text-slate-500">Rp</span><input name="{{ $field }}" type="text" inputmode="numeric" value="{{ old($field, $default) }}" data-currency-input @if($required) required @endif class="w-full rounded-xl pl-11"></div></label>@endforeach
            <div class="grid grid-cols-2 gap-3"><label class="grid gap-1 text-sm font-bold">Mulai kegiatan<input name="activity_starts_at" type="date" class="rounded-xl"></label><label class="grid gap-1 text-sm font-bold">Akhir kegiatan<input name="activity_ends_at" type="date" class="rounded-xl"></label><label class="grid gap-1 text-sm font-bold">Mulai pelaporan<input name="reporting_starts_at" type="date" class="rounded-xl"></label><label class="grid gap-1 text-sm font-bold">Akhir pelaporan<input name="reporting_ends_at" type="date" class="rounded-xl"></label></div><button class="primary-action">Simpan periode</button></div>
        </form>
        <section class="surface-card overflow-hidden"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-bold text-ink">Daftar periode</h3></div><div class="divide-y divide-slate-100">@forelse($periods as $period)<article class="flex flex-wrap items-center justify-between gap-4 px-5 py-4"><div><div class="flex items-center gap-2"><p class="font-bold text-ink">{{ $period->year }} · {{ $period->quarter }}</p>@if($period->is_active)<span class="status-pill bg-teal-50 text-brand">Aktif</span>@endif</div><p class="mt-1 text-sm text-slate-600">Target periode Rp {{ number_format($period->target_amount, 0, ',', '.') }} · Buffer Rp {{ number_format($period->buffer_amount, 0, ',', '.') }}</p></div>@unless($period->is_active)<form method="POST" action="{{ route('periods.activate', $period) }}">@csrf<button class="rounded-xl border border-teal-200 px-3 py-2 text-sm font-bold text-brand hover:bg-teal-50">Aktifkan</button></form>@endunless</article>@empty<p class="px-5 py-10 text-sm text-slate-500">Belum ada periode.</p>@endforelse</div></section>
    </section>
    <section class="mt-5 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div class="rounded-2xl border border-amber-200 bg-amber-50 p-6"><span class="status-pill bg-white text-amber-800">Checkpoint</span><h3 class="mt-4 text-lg font-bold text-amber-950">Rekam progres tim saat ini</h3><p class="mt-2 text-sm leading-6 text-amber-900">Snapshot menyimpan jumlah assignment, perusahaan dikontak, konfirmasi PIC, nilai indikatif, dan cakupan sasaran utama periode aktif.</p><form method="POST" action="{{ route('checkpoints.store') }}" class="mt-5">@csrf<button class="rounded-xl bg-amber px-4 py-2.5 text-sm font-bold text-ink">Buat checkpoint sekarang</button></form></div><section class="surface-card overflow-hidden"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-bold text-ink">Checkpoint terbaru</h3></div><div class="divide-y divide-slate-100">@forelse($snapshots as $snapshot)<article class="flex items-center justify-between gap-3 px-5 py-4 text-sm"><div><p class="font-bold text-ink">{{ $snapshot->period->year }} · {{ $snapshot->period->quarter }} · {{ $snapshot->checkpoint_at->format('d M Y') }}</p><p class="mt-1 text-xs text-slate-500">Kontak {{ $snapshot->contacted_company_count }}/{{ $snapshot->assigned_company_count }} · Konfirmasi {{ $snapshot->confirmed_company_count }}</p></div><p class="text-right text-xs font-bold text-brand">Rp {{ number_format($snapshot->indicated_amount / 1000000000, 1, ',', '.') }} M</p></article>@empty<p class="px-5 py-10 text-sm text-slate-500">Belum ada checkpoint.</p>@endforelse</div></section></section>
</x-layouts.app>
