<x-layouts.app :title="'Data Terpadu Proyek dan LKPM'">
    <section class="space-y-5">
        <div class="flex flex-col justify-between gap-4 lg:flex-row lg:items-end">
            <div><p class="page-eyebrow">Data induk dan pelaporan</p><h2 class="page-title">Data Terpadu</h2><p class="page-copy">Satu baris per proyek DP.Proyek dengan LKPM terbaru yang sesuai filter. Buka detail untuk melihat seluruh riwayat LKPM dan kolom sumber.</p></div>
            <span class="status-pill self-start bg-teal-50 text-brand lg:self-auto">{{ number_format($projects->total()) }} proyek ditemukan</span>
        </div>

        <form method="GET" class="surface-card grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-6">
            <label class="lg:col-span-2"><span class="mb-1.5 block text-xs font-bold text-slate-600">Cari perusahaan, NIB, kode proyek, atau KBLI</span><input name="search" value="{{ $filters['search'] ?? '' }}" class="form-input" placeholder="Contoh: PT Maju atau 201912..." /></label>
            <label><span class="mb-1.5 block text-xs font-bold text-slate-600">Data</span><select name="source" class="form-input"><option value="all" @selected(($filters['source'] ?? 'all') === 'all')>Semua proyek</option><option value="lkpm" @selected(($filters['source'] ?? '') === 'lkpm')>Memiliki LKPM</option><option value="without_report" @selected(($filters['source'] ?? '') === 'without_report')>Tanpa riwayat LKPM</option></select></label>
            <label><span class="mb-1.5 block text-xs font-bold text-slate-600">Tahun LKPM</span><select name="year" class="form-input"><option value="">Semua tahun</option>@foreach($years as $year)<option value="{{ $year }}" @selected((string)($filters['year'] ?? '') === (string)$year)>{{ $year }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block text-xs font-bold text-slate-600">Periode LKPM</span><select name="quarter" class="form-input"><option value="">Semua periode</option>@foreach($quarters as $quarter)<option value="{{ $quarter }}" @selected(($filters['quarter'] ?? '') === $quarter)>{{ $quarter }}</option>@endforeach</select></label>
            <label><span class="mb-1.5 block text-xs font-bold text-slate-600">Status LKPM</span><select name="status" class="form-input"><option value="">Semua status</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ $status }}</option>@endforeach</select></label>
            <div class="flex items-end gap-2 sm:col-span-2 lg:col-span-6"><button class="primary-action" type="submit">Terapkan filter</button><a href="{{ route('integrated-data.index') }}" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-50">Reset</a></div>
        </form>

        <section class="surface-card overflow-hidden">
            <div class="border-b border-slate-100 px-5 py-4"><h3 class="font-bold text-ink">Daftar proyek dan LKPM</h3><p class="mt-1 text-xs text-slate-500">Nilai realisasi hanya berasal dari data LKPM yang tersedia pada proyek tersebut.</p></div>
            <div class="hidden overflow-x-auto xl:block"><table class="min-w-[1180px] divide-y divide-slate-100 text-sm"><thead class="bg-slate-50/80 text-left text-[11px] font-bold uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3.5">Perusahaan / NIB</th><th class="px-5 py-3.5">DP.Proyek</th><th class="px-5 py-3.5">Rencana investasi</th><th class="px-5 py-3.5">LKPM terbaru</th><th class="px-5 py-3.5">Realisasi akumulatif</th><th class="px-5 py-3.5"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($projects as $project)@php($report = $project->reports->first())<tr class="transition hover:bg-teal-50/40"><td class="px-5 py-4"><p class="font-bold text-ink">{{ $project->company->name }}</p><p class="mt-1 text-xs text-slate-500">NIB {{ $project->company->nib }}</p></td><td class="px-5 py-4"><p class="font-semibold text-slate-700">{{ $project->project_code }}</p><p class="mt-1 max-w-55 text-xs text-slate-500">{{ $project->kbli ?: 'KBLI belum tersedia' }} · {{ $project->sector ?: 'Sektor belum dipetakan' }}</p></td><td class="px-5 py-4 font-semibold text-slate-700">Rp {{ number_format($project->planned_investment, 0, ',', '.') }}</td><td class="px-5 py-4">@if($report)<p class="font-semibold text-slate-700">{{ $report->report_year }} · {{ $report->report_quarter }}</p><span class="status-pill mt-1 {{ $report->report_status === 'Disetujui' ? 'bg-teal-50 text-brand' : 'bg-amber-50 text-amber-800' }}">{{ $report->report_status }}</span>@else<span class="status-pill bg-slate-100 text-slate-600">Belum ada LKPM</span>@endif</td><td class="px-5 py-4 font-semibold text-slate-700">{{ $report ? 'Rp '.number_format($report->accumulated_investment, 0, ',', '.') : '—' }}</td><td class="px-5 py-4 text-right"><a href="{{ route('integrated-data.show', $project) }}" class="text-sm font-bold text-brand hover:underline">Detail lengkap →</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-14 text-center text-slate-500">Tidak ada data yang sesuai dengan filter.</td></tr>@endforelse</tbody></table></div>
            <div class="grid divide-y divide-slate-100 xl:hidden">@forelse($projects as $project)@php($report = $project->reports->first())<article class="space-y-3 p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="truncate font-bold text-ink">{{ $project->company->name }}</p><p class="mt-1 text-xs text-slate-500">NIB {{ $project->company->nib }}</p></div>@if($report)<span class="status-pill shrink-0 {{ $report->report_status === 'Disetujui' ? 'bg-teal-50 text-brand' : 'bg-amber-50 text-amber-800' }}">{{ $report->report_status }}</span>@else<span class="status-pill shrink-0 bg-slate-100 text-slate-600">Belum ada LKPM</span>@endif</div><div class="grid grid-cols-2 gap-3 text-xs"><div class="rounded-xl bg-slate-50 p-3"><p class="text-slate-500">Kode proyek</p><p class="mt-1 break-all font-bold text-ink">{{ $project->project_code }}</p></div><div class="rounded-xl bg-slate-50 p-3"><p class="text-slate-500">Realisasi LKPM</p><p class="mt-1 font-bold text-ink">{{ $report ? 'Rp '.number_format($report->accumulated_investment, 0, ',', '.') : '—' }}</p></div></div><a href="{{ route('integrated-data.show', $project) }}" class="inline-flex text-sm font-bold text-brand">Lihat detail lengkap →</a></article>@empty<p class="px-5 py-14 text-center text-sm text-slate-500">Tidak ada data yang sesuai dengan filter.</p>@endforelse</div>
        </section>
        <div>{{ $projects->links() }}</div>
    </section>
</x-layouts.app>
