<x-layouts.app title="Rekonsiliasi Kode Proyek">
    <div><p class="text-sm font-medium text-brand">Kepala Bagian</p><h2 class="mt-1 text-3xl font-semibold text-ink">Rekonsiliasi kode proyek</h2><p class="mt-2 text-slate-600">Hubungkan kode LKPM ke Id Proyek DP.Proyek hanya jika sudah terverifikasi dari sumber resmi. Sistem tidak melakukan pencocokan berdasarkan nama perusahaan.</p></div>
    <section class="mt-7 grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
        <form method="POST" action="{{ route('reconciliations.store') }}" class="rounded-xl bg-white p-6 shadow-sm ring-1 ring-slate-200">@csrf<h3 class="font-semibold text-ink">Tambah pemetaan terverifikasi</h3><div class="mt-5 grid gap-4"><label class="grid gap-1 text-sm font-medium">No Kode Proyek LKPM<input name="lkpm_project_code" required class="rounded-lg border-slate-300" placeholder="Contoh: 202112-1512-..."></label><label class="grid gap-1 text-sm font-medium">Id Proyek DP.Proyek<input name="project_code" required class="rounded-lg border-slate-300" placeholder="Contoh: R-2019..."></label><button class="rounded-lg bg-brand px-4 py-2.5 text-sm font-semibold text-white">Simpan pemetaan</button></div></form>
        <div class="rounded-xl border border-amber-200 bg-amber-50 p-6"><p class="text-sm font-medium text-amber-900">Laporan belum terhubung</p><p class="mt-2 text-4xl font-semibold text-amber-950">{{ number_format($unlinkedReportCount) }}</p><p class="mt-2 text-sm leading-6 text-amber-900">Laporan ini tetap tersimpan sebagai data sumber, tetapi tidak digunakan untuk menghitung gap per proyek sebelum dipetakan.</p></div>
    </section>
    <section class="mt-7 grid gap-6 xl:grid-cols-2"><div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="border-b border-slate-200 px-5 py-4"><h3 class="font-semibold text-ink">Kode LKPM belum terhubung</h3></div><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">No Kode Proyek</th><th class="px-5 py-3">Jumlah laporan</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($unlinkedCodes as $row)<tr><td class="px-5 py-3 font-mono text-xs">{{ $row->project_code }}</td><td class="px-5 py-3">{{ number_format($row->report_count) }}</td></tr>@empty<tr><td colspan="2" class="px-5 py-8 text-center text-slate-500">Semua laporan telah terhubung.</td></tr>@endforelse</tbody></table><div class="p-5">{{ $unlinkedCodes->links() }}</div></div>
    <div class="overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><div class="border-b border-slate-200 px-5 py-4"><h3 class="font-semibold text-ink">Pemetaan terbaru</h3></div><div class="divide-y divide-slate-100">@forelse ($recentMappings as $mapping)<div class="px-5 py-4 text-sm"><p class="font-mono text-xs text-slate-500">{{ $mapping->lkpm_project_code }}</p><p class="mt-1 font-medium text-ink">{{ $mapping->project->project_code }} · {{ $mapping->project->company->name }}</p><p class="mt-1 text-xs text-slate-500">oleh {{ $mapping->mappedBy->name }}</p></div>@empty<p class="px-5 py-8 text-sm text-slate-500">Belum ada pemetaan terverifikasi.</p>@endforelse</div></div></section>
</x-layouts.app>
